# Generated by Django 5.0.7 on 2024-08-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_brands_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isFeatured',
            new_name='is_featured',
        ),
    ]
