# Generated by Django 5.0.7 on 2024-08-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_clothestype_product_clothes_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clothes_type',
            new_name='clothesType',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
