# Generated by Django 5.0.7 on 2024-08-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_created_at_alter_cart_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
